<h1>Parametry <?= $this->escape($this->product->getProduct_name()); ?></h1>

<?= $this->partial('partial/product_navigation.phtml', array('product' => $this->product, 'active_nav' => 'parameter')); ?>

<div class="row">
    <? if ($this->isParameters) { ?>

        <div class="col-md-12">

            <p><strong><?= $this->variantParametersInfo; ?></strong></p>
            
            <form action="<?php echo $this->escape($this->form->getAction()) ?>"
                  method="<?php echo $this->escape($this->form->getMethod()) ?>"
                  id="add-parameter-unit-form"
                  enctype="multipart/form-data">

                <? $element = $this->form; ?>


                <div id="parameter-dial-items">
                    <?
                    foreach ($element as $elementItem) {
                        ?>

                        <div class="row">
                            <div class="col-lg-3">
                                <?= $elementItem->getLabel(); ?>
                            </div>
                            <div class="col-lg-3">
                                <?= $elementItem; ?>
                            </div>
                        </div>

                        <?
                    }
                    ?>
                </div>
            </form>
        </div>
    <? } else { ?>
        <p><?= $this->variantParametersInfo; ?></p>
    <? } ?>
</div>