<h1>Vložení stavu objednávky</h1>

<div class="container">
    <div class="row">
        <form action="<?php echo $this->escape($this->form->getAction()) ?>"
              method="<?php echo $this->escape($this->form->getMethod()) ?>"
              enctype="multipart/form-data">

            <? $element = $this->form; ?>

            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('order_state_name')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('order_state_name'); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('order_state_color')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('order_state_color'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('order_state_text')->getLabel(); ?>
                </div>
                <div class="col-lg-7">
                    <?= $element->getElement('order_state_text'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('submit'); ?>
                </div>
            </div>   
        </form>
    </div>
</div>