<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->headTitle . ' | Yagga.cz');
echo $this->doctype('HTML5');
?>

<html lang="en">
    <head>    
        <? $this->headMeta()->setName('description', $this->metaDescription); ?>
        <? $this->headMeta()->setName('robots', 'all, index, follow'); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="HandheldFriendly" content="true">
        <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">

        <!-- begin facebook meta image -->
        <? if ($this->facebookImageUrl) { ?>
            <meta property="og:image" content="<?= $this->facebookImageUrl ?>"/>
            <link rel="image_src" type="image/jpeg" href="<?= $this->facebookImageUrl ?>" />
        <? } ?>
        <!-- end facebook meta image -->    
            
        <!-- begin facebook meta -->
        <meta property="og:title" content="Pusinka a vzkaz od: <?= $this->escape($this->kisssender->getKisssender_sender_name()); ?>" />
        <meta property="og:description" content="<?= $this->escape($this->kisssender->getKisssender_text()); ?>" />
            <!-- end facebook meta  -->

        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
            <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
        <![endif]-->

        <link rel="shortcut icon" href="/images/default/favico.ico" />

        <!-- canonical pages -->
        <? if ($this->canonicalPage) { ?>
            <link rel="canonical" href="<?= $this->canonicalPage ?>" />
        <? } ?>
        <?php echo $this->headLink(); ?>
        <?php /* echo $this->jQuery()->enable(); */ ?>


        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-57765949-1', 'auto');
            ga('require', 'linkid', 'linkid.js');
            ga('require', 'displayfeatures');
            ga('send', 'pageview');

        </script>


        <!--Start of Zopim Live Chat Script-->
        <!--
        <script type="text/javascript">
            window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
                    d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
                        _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
                $.src='//v2.zopim.com/?2gphzLiHEWUWH8qGQn57WibXC0ZQaDE3';z.t=+new Date;$.
                    type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
        </script>
        --->
        <!--End of Zopim Live Chat Script-->


        <!--Start of Facebook remarketing Script-->
        <script>(function() {
            var _fbq = window._fbq || (window._fbq = []);
            if (!_fbq.loaded) {
                var fbds = document.createElement('script');
                fbds.async = true;
                fbds.src = '//connect.facebook.net/en_US/fbds.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(fbds, s);
                _fbq.loaded = true;
            }
            _fbq.push(['addPixelId', '749061731852880']);
        })();
        window._fbq = window._fbq || [];
        window._fbq.push(['track', 'PixelInitialized', {}]);
        </script>
    <noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=749061731852880&amp;ev=PixelInitialized" /></noscript>
    <!--End of Facebook remarketing Script-->


</head>
<body id="kissender-sendkiss">

    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/cs_CZ/sdk.js#xfbml=1&appId=132987736773044&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    
    <!-- obsah -->

    <div class="row sendkiss-detail" id="sendkiss">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-5">
                <a href="/"><img alt="yagga" src="/images/default/yagga-square-120.png"></a>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-7">
                <ul class="list-inline social-buttons">
                    <li><a target="_blank" href="http://www.facebook.com/yaggacz" class="facebook"><i class="fa fa-facebook fa-2x"></i></a></li>
                    <li><a target="_blank" href="http://www.instagram.com/yagga.cz" class="instagram"><i class="fa fa-instagram fa-2x"></i></a></li>
                    <li><a target="_blank" href="https://www.youtube.com/channel/UC2zjPieb4gA8VGOKFG620AA" class="youtube"><i class="fa fa-youtube fa-2x"></i></a></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
                <div class="kiss-hearts-section">
                    <div class="kiss-hearts-wrap">
                        <div class="kiss-mouth" href="/poslipusinku/formular"></div>
        <!--                <img alt="yagga" class="img-responsive" src="/images/default/kisssender/kiss-mouth.png">-->
                    </div>
                    <h1>Pusinku a vzkaz posílá:</h1>
                    <h2><?= $this->escape($this->kisssender->getKisssender_sender_name()); ?></h2>
                    <div class="kiss-text"><?= $this->escape($this->kisssender->getKisssender_text()); ?></div>
                </div>
            </div>

        </div>
        <div class="row text-center">
            <a class="btn-sendkiss" target="_blank" href="/poslipusinku/formular">Chci poslat pusinku!</a>
        </div>

        
        <div class="row text-center">
            <div class="fb-share-button" data-href="<?= $this->uri ?>" data-layout="box_count"></div>
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center">
                    <h3>Sledujte nás</h3>
                    <ul class="list-inline social-buttons">
                        <li><a target="_blank" href="http://www.facebook.com/yaggacz" class="facebook"><i class="fa fa-facebook fa-2x"></i></a></li>
                        <li><a target="_blank" href="http://www.instagram.com/yagga.cz" class="instagram"><i class="fa fa-instagram fa-2x"></i></a></li>
                        <li><a target="_blank" href="https://www.youtube.com/channel/UC2zjPieb4gA8VGOKFG620AA" class="youtube"><i class="fa fa-youtube fa-2x"></i></a></li>
                    </ul>
                    <p>Yagga.cz © 2014</p>
                </div>
            </div>
        </div>
    </footer>


    <?php
    $this->jQuery()->enable();
    echo $this->jQuery();
    ?>

</body>
</html>