

<? if(!Zend_Auth::getInstance()->hasIdentity()){ ?>
<div class="login-form">
<form class="form-signin" action="<?php echo $this->escape($this->form->getAction()) ?>"
      method="<?php echo $this->escape($this->form->getMethod()) ?>"
      enctype="multipart/form-data">
    <h2>Přihlášení</h2>
    <?= $this->form->getElement('admin_email'); ?>
    <?= $this->form->getElement('admin_password'); ?>
    <?= $this->form->getElement('submit'); ?>

</form>
</div>
<? } ?>