<!--
<div class="row shop-info-sendkiss text-center">
<a target="_blank" href="/poslipusinku"><img src="/images/default/kisssender/kiss-mouth-50.png" alt="yagga" />Pošli pusinku a vzkaz - originální elektronická pusinka</a>
</div>
-->

<div class="shop-info" id="sec2">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="col-md-3 col-sm-6 text-center">
                    <div class="shop-info-item">
                        <i class="fa fa-history fa-3x"></i> 
                        <h4>Doručení do druhého dne</h4>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 text-center">
                    <div class="shop-info-item">
                        <i class="fa fa-truck fa-3x"></i> 
                        <h4>Doprava od 69 Kč</h4>
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6 text-center">
                    <div class="shop-info-item">
                        <i class="fa fa-shield fa-3x"></i> 
                        <h4>Vrácení zboží do 14 dnů</h4>
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6 text-center">
                    <div class="shop-info-item">
                        <i class="fa fa-envelope-o fa-3x"></i> 
                        <h4><!-- +420 775 591 082<br /> --><span class="email-address" data-email="info" data-domain="yagga.cz"></span></h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>