
<div class="container">
    <div class="row">

        <h1>Editace faktury</h1>

        
        <form action="<?php echo $this->escape($this->form->getAction()) ?>"
              method="<?php echo $this->escape($this->form->getMethod()) ?>"
              id="add-product-form"
              class="include-image-upload"
              enctype="multipart/form-data">

            <? $element = $this->form; ?>
            
            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('invoice_creating_date')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('invoice_creating_date'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('invoice_due_date')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('invoice_due_date'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('submit'); ?>
                </div>
            </div>   
        </form>
    </div>
</div>  
