
<div class="error-page page-wrap">
    <div class="container error-page-wrap">
        <div class="row text-center">
            <i class="fa fa-frown-o fa-5x"></i>
            <h2>Ajéje...</h2>
            <h1>Omlouváme se, požadovaná stránka neexistuje</h1>
            <p>Chybový kód 404</p>

            <h3>Chyba mohla nastat z těchto důvodů:</h3>
            <ul>
                <li>
                    Špatně napsaná URL adresa nebo zastaralá oblíbená položka
                </li>
                <li>
                    Zastaralý odkaz z výsledků vyhledavače
                </li>
                <li>
                    Neplatný interní odkaz v rámci aktuálních internetovách stránek
                </li>
                <li>
                    Neplatný odkaz z jiných internetových stránek
                </li>
                <li>
                    Je možné, že stránka byla přemístěna nebo odstraněna
                </li>
            </ul>
            <div class="text-center">
                <a class="btn btn-default" href="/">Pokračovat můžete zde</a>
            </div>
        </div>
    </div>
</div>
