<div class="container">
    <div class="row">
        <h1>Vložení stránky</h1>

        <form action="<?php echo $this->escape($this->form->getAction()) ?>"
              method="<?php echo $this->escape($this->form->getMethod()) ?>"
              id="add-page-form"
              enctype="multipart/form-data">

            <? $element = $this->form; ?>

            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('page_name')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('page_name'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('page_url')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('page_url'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('page_seo_title')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('page_seo_title'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('page_seo_meta_description')->getLabel(); ?>
                </div>
                <div class="col-lg-7">
                    <?= $element->getElement('page_seo_meta_description'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('page_text')->getLabel(); ?>
                </div>
                <div class="col-lg-7">
                    <?= $element->getElement('page_text'); ?>
                </div>
            </div>
            
            
            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('page_is_active')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('page_is_active'); ?>
                </div>
            </div>
            
            
            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('submit'); ?>
                </div>
            </div>   
        </form>
    </div>
</div>