<h1>Vložení parametru</h1>

<div class="container">
    <div class="row">
        <form action="<?php echo $this->escape($this->form->getAction()) ?>"
              method="<?php echo $this->escape($this->form->getMethod()) ?>"
              id="add-parameter-form"
              enctype="multipart/form-data">

            <? $element = $this->form; ?>


            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_name')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_name'); ?>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_type')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_type'); ?>
                </div>
            </div>


            <div id="parameter_unit" class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_parameter_unit_id')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_parameter_unit_id'); ?>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_note')->getLabel(); ?>
                </div>
                <div class="col-lg-7">
                    <?= $element->getElement('parameter_note'); ?>
                </div>
            </div>


            <div id="parameter-dial">
                <div id="parameter-dial-items">
                    <?
                    foreach ($element as $elementItem) {
                        if ($elementItem->getBelongsTo() == 'parameter_dial_value') {
                            ?>

                            <div class="row">
                                <div class="col-lg-3">
                                    <?= $elementItem->getLabel(); ?>
                                </div>
                                <div class="col-lg-3">
                                    <?= $elementItem; ?>
                                </div>
                            </div>

                            <?
                        }
                    }
                    ?>
                </div>
                <div id="parameter-dial-btn">
                    <div class="row">
                        <div class="col-lg-offset-3 col-lg-3">
                            <?= $element->getElement('add_dial_btn'); ?>
                        </div>
                    </div>   
                </div>
            </div>


            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_category')->getLabel(); ?>
                </div>
                <div class="col-lg-7">
                    <div class="checkbox">
                        <?= $element->getElement('parameter_category'); ?>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('submit'); ?>
                </div>
            </div>   
        </form>
    </div>
</div>