<h1>Úprava párování kategorie</h1>

<div class="container">
    <div class="row">
        <form action="<?php echo $this->escape($this->form->getAction()) ?>"
              method="<?php echo $this->escape($this->form->getMethod()) ?>"
              enctype="multipart/form-data">

            <? $element = $this->form; ?>

            <? $categoryAffiliate = $this->categoryAffiliateById; ?>

            <div class="row">
                <div class="col-lg-3">
                    Affiliate kategorie
                </div>
                <div class="col-lg-3">
                    <?= $categoryAffiliate->getCategory_affiliate_category_name(); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('category_id')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('category_id'); ?>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('submit'); ?>
                </div>
            </div>   
        </form>
    </div>
</div>