<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

        <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

        <title>Yagga.cz</title>
    </head>
    <body style="background-image: url('http://www.yagga.cz/images/default/heart-pattern.png'); background-color: #ead9ce; font-family: Arial, Verdana, Helvetica, sans-serif; width: 100%; height: 100%">
        <table style="" border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <td>
                    <div id="wrap" style="width: 800px; margin: 30px auto;">
                        <div id="head" style="margin: 30px 0; padding: 0 25px;">
                            <div style="height: 50px;">
                                <div id="logo" style="float: left; margin-top: 3px;">
                                    <a href="http://www.yagga.cz">
                                        <img src="http://www.yagga.cz/images/default/yagga-logo.png" style="height: 35px; width: 137px" alt="Yagga.cz"/>
                                    </a>
                                </div>
                            </div>


                            <div id="content" style="font-size: 14px; color: #3b3b3b; text-align: center;">

                                <img style="width: 150px;" src="http://www.yagga.cz/images/default/kisssender/kiss-mouth.png" alt="Pusinka :-*" />
                                <!--                                <h1 style="font-weight: bold; font-size: 24px; color: black;">Potvrzení objednávky</h1> -->
                                <h2 style="font-weight: bold; font-size: 3.1em; padding-top: 0px; margin-top: 10px; margin-bottom: 4px;  color:#3b3b3b; font-family: 'Lobster', cursive;"><?= $this->escape($this->sender_name); ?></h2>
                                <h3 style="font-weight: bold; font-size: 2.1em; padding-top: 0px; margin-top: 10px; color:#3b3b3b; font-family: 'Lobster', cursive;">
                                    Vám posílá pusinku a vzkaz
                                </h3>

                                <a href="http://www.yagga.cz/poslipusinku/vzkaz/<?= $this->hash ?>" style="width: 200px; background-color: rgb(250, 13, 114); display: block; text-align: center; margin: 0px auto; padding: 15px; color: rgb(255, 255, 255); text-decoration: none; border: 2px solid rgb(92, 31, 31); font-weight: 100; border-radius: 2px;">
                                    <span style="display: block; font-size: 21px;">VYZVEDNOUT</span>
                                </a>

                                <p style="margin-top: 50px; margin-bottom: 2px;  font-size: 17px;">I Vy můžete někoho potěšit a poslat mu pusinku a vzkaz.</p>
                                <p style="margin: 0px; font-size: 17px;">Více na <a href="http://www.yagga.cz/poslipusinku">www.yagga.cz/poslipusinku</a></p>

                            </div>


                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </body>
</html>   
