<h1>Kategorie</h1>


<a href="<?= $this->url(array('module' => 'admin', 'controller' => 'category', 'action' => 'add'), null, true) ?>" type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Vložit kategorii</a>

<a href="<?= $this->url(array('module' => 'admin', 'controller' => 'categoryaffiliate', 'action' => 'index'), null, true) ?>" type="button" class="btn btn-default">Párování kategorií</a>


<div class="table-responsive">
    <? if (!empty($this->categories)) { ?>
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Aktivní</td>
                    <td>Pořadí</td>
                    <td>Název</td>
                    <td>Struktura</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                <? foreach ($this->categories as $category) { ?>
                    <tr>
                        <td><?= $category->getCategory_id() ?></td>
                        <td><?= $category->getCategory_is_active() ?></td>
                        <td><?= $category->getCategory_order() ?></td>
                        <td><span style="padding-left: <?= 25*$category->getCategory_level() ?>px"><?= $category->getCategory_name() ?></span></td>
                        <td><?= $category->getCategory_structure() ?></td>
                        <td class="action-buttons">
                            <div class="btn-group">
                                <a class="btn btn-default" href="<?= $this->url(array('module' => 'admin', 'controller' => 'category', 'action' => 'edit', 'id' => $category->getCategory_id()), null, true) ?>"><span class="glyphicon glyphicon-pencil"></span></a>
                                <a class="btn btn-default" href="<?= $this->url(array('module' => 'admin', 'controller' => 'category', 'action' => 'delete', 'id' => $category->getCategory_id()), null, true) ?>" onclick="return confirm('Opravdu smazat?')"><span class="glyphicon glyphicon-trash"></span></a>
                            </div>
                        </td>
                    </tr>
                <? } ?>
            </tbody>
        </table>
    <? } ?>
</div>