<h1>Pusinky</h1>



<? if (!empty($this->kisssenders)) { ?>
    <div class="table-responsive">

        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <td>#</td>
                    <td>Jméno</td>
                    <td>Příjemce</td>
                    <td>Odesílatel</td>
                    <td>Vzkaz</td>
                    <td>Lat, Lng</td>
                    <td>IP</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                <? foreach ($this->kisssenders as $kisssender) {
                    ?>
                    <tr>
                        <td>
                            <?= $kisssender->getKisssender_id(); ?>
                        </td>
                        <td>
                            <?= $kisssender->getKisssender_sender_name(); ?>
                        </td>

                        <td>
                            <?= $kisssender->getKisssender_email_to(); ?>
                        </td>
                        <td>
                            <?= $kisssender->getKisssender_email_from(); ?>
                        </td>
                        <td>
                            <? if ($kisssender->getKisssender_text()) { ?>
                                <span class="tooltip-init" data-toggle="tooltip" title="<?= $kisssender->getKisssender_text(); ?>"><span class="glyphicon glyphicon-comment"></span></span>
                            <? } ?>
                        </td>
                        <td>
                            <? if ($kisssender->getKisssender_latitude() && $kisssender->getKisssender_longitude()) { ?>
                                <?= $kisssender->getKisssender_latitude(); ?>, <?= $kisssender->getKisssender_longitude(); ?>
                            <? } ?>
                        </td>
                        <td>
                            <?= $kisssender->getKisssender_ip_address(); ?>
                        </td>
                        <td class="action-buttons">
                            <div class="btn-group">
                                <a class="btn btn-default" target="_blank" href="<?= $this->url(array('module' => 'default', 'controller' => 'kisssender', 'action' => 'detail', 'hash' => $kisssender->getKisssender_hash()), 'kisssender_detail_url', true) ?>"><span class="glyphicon glyphicon-link"></span></a>
                            </div>
                        </td>
                    </tr>
                <? } ?>
            </tbody>
        </table>
    </div>


    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('url' => 'admin/kisssender/')); ?>


<? } ?>


