<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <title>Yagga.cz</title>
    </head>
    <body style="background-color: #ececec; font-family: Arial, Verdana, Helvetica, sans-serif; width: 100%; height: 100%">
        <table style="background-color:  #ececec;" border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <td>
                    <div id="wrap" style="background-color: white; border-width: 1px; border-style: solid; border-color: #c5c3c3; width: 800px; margin: 30px auto;">
                        <div id="head" style="margin: 30px 0; padding: 0 25px;">
                            <div style="height: 50px;">
                                <div id="logo" style="float: left; margin-top: 3px;">
                                    <a href="http://www.yagga.cz">
                                        <img src="http://www.yagga.cz/images/default/yagga-logo.png" style="height: 35px; width: 137px" alt="Yagga.cz"/>
                                    </a>
                                </div>
                            </div>