                            <p style="padding-bottom: 7px; color:#3b3b3b; font-size: 14px;">Věříme, že jste u nás rádi nakoupili a i nadále budete našimi zákazníky.</p>

                            <p style="padding-bottom: 15px; color:#3b3b3b; font-size: 14px;">
                                S přáním pěkného dne,<br />
                                Martina Jedináková<br />
                                <a href="http://www.yagga.cz">yagga.cz</a>
                            </p>

                        </div>
                    </div>
                    <div style=" margin: 0; padding: 0; text-align: center; color: #9c9c9c;"><h4>Tento e-mail je generován automaticky, prosíme, neodpovídejte na něj.</h4></div>
                </td>
            </tr>
        </table>
    </body>
</html>   