<h1>Úprava jednotky</h1>

<div class="container">
    <div class="row">
        <form action="<?php echo $this->escape($this->form->getAction()) ?>"
              method="<?php echo $this->escape($this->form->getMethod()) ?>"
              id="add-parameter-unit-form"
              enctype="multipart/form-data">

            <? $element = $this->form; ?>

            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_unit_name')->getLabel(); ?>
                </div>
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_unit_name'); ?>
                </div>
            </div>
            
            

            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_unit_shortcut')->getLabel(); ?>
                </div>
                <div class="col-lg-2">
                    <?= $element->getElement('parameter_unit_shortcut'); ?>
                </div>
            </div>
            
            
            

            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('parameter_unit_note')->getLabel(); ?>
                </div>
                <div class="col-lg-7">
                    <?= $element->getElement('parameter_unit_note'); ?>
                </div>
            </div>
            
            
            
            <div class="row">
                <div class="col-lg-3">
                    <?= $element->getElement('submit'); ?>
                </div>
            </div>   
        </form>
    </div>
</div>