<h1>Editace produktu</h1>


<div class="container">
    <div class="row">
        <? if (!empty($this->orderItem)) { ?>
            <div class="col-lg-6">
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <tbody>
                            <tr>
                                <th>Id</th>
                                <td><?= $this->orderItem->getOrder_item_id(); ?></td>
                            </tr>
                            <tr>
                                <th>Nazev</th>
                                <td><?= $this->orderItem->getOrder_item_product_name(); ?></td>
                            </tr>
                            <? if ($this->orderItem->getOrder_item_variant_name()) { ?>
                                <tr>
                                    <th>Varianta</th>
                                    <td><?= $this->orderItem->getOrder_item_variant_name(); ?></td>
                                </tr>
                            <? } ?>
                            <tr>
                                <th>Ks</th>
                                <td><?= $this->orderItem->getOrder_item_pieces(); ?></td>
                            </tr>
                            <tr>
                                <th>Cena za ks</th>
                                <td><?= $this->orderItem->getOrder_item_price(); ?></td>
                            </tr>
                            <tr>
                                <th>Cena celkem</th>
                                <td><?= $this->orderItem->getOrder_item_pieces() * $this->orderItem->getOrder_item_price(); ?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-lg-6">
                <form action="<?php echo $this->escape($this->form->getAction()) ?>"
                      method="<?php echo $this->escape($this->form->getMethod()) ?>"
                      id="edit-order-form"
                      enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-lg-5 text-right">
                            <?= $this->form->getElement('order_item_pieces')->getLabel(); ?>
                        </div>
                        <div class="col-lg-4">
                            <?= $this->form->getElement('order_item_pieces'); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-5 text-right">
                            <?= $this->form->getElement('order_item_price')->getLabel(); ?>
                        </div>
                        <div class="col-lg-4">
                            <?= $this->form->getElement('order_item_price'); ?>
                        </div>
                    </div>


                    <? if ($this->form->getElement('order_item_variant_id')) { ?>
                        <div class="row">
                            <div class="col-lg-5 text-right">
                                <?= $this->form->getElement('order_item_variant_id')->getLabel(); ?>
                            </div>
                            <div class="col-lg-4">
                                <?= $this->form->getElement('order_item_variant_id'); ?>
                            </div>
                        </div>
                    <? } ?>



                    <div class="row">
                        <div class="col-lg-4 col-lg-offset-5">
                            <?= $this->form->getElement('submit'); ?>

                        </div>
                    </div>
                </form>
            </div>
        <? } ?>

    </div>
</div>